<?php
/**
 * Created by PhpStorm.
 * User: bryan
 * Date: 2/4/15
 * Time: 6:59 PM
 */

/**
 * Implements hook_block_info().
 */
function mhquiz_block_info() {
  $blocks['moneyquiz'] = array(
    'info' => t('Moneyharmony Quiz'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mhquiz_block_view($delta = '') {
  switch($delta) {
    case 'moneyquiz':
      $block['content'] = drupal_get_form('mhquiz_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_form().
 */
function mhquiz_form($form, &$form_state) {

  // Was the form submitted already?
  if (isset($form_state['submitted']) && $form_state['submitted']) {
    $form['submission'] = array(
      '#markup' => _mhquiz_results_output($form_state['values']['results'])
    );
  }
  else { // If not, then build the form
    $intro_text = "<p>This quiz will show you which of five major money personality
types most closely matches your own tendencies: Hoarder, Spender, Money Monk,
Avoider, or Amasser. (If you're the sixth major type — a 'Money Worrier' — you already know
it!) Bear in mind that each type has both good qualities and shortcomings, and
that most people are in fact a combination of types. This isn't a statistically
valid survey, of course — just a way to help determine which money types prevail
in your makeup. For each of the 20 statements in the quiz, choose the answer
that strikes you first as being closest to your attitude. Record your answers
on a separate sheet of paper. There is no right answer. Just be as honest with
yourself as you can — and have fun!</p>";
    $intro_text .= "<p>To find out more about all of the money personality types,
  check out Chapter Four of <a href='/books-resources#mhrmc'>Money Harmony: A Road Map for Individuals and Couples</a>, by Olivia Mellan
  and Sherry Christie.</p>";

    $form['intro_text'] = array(
      '#markup' => t($intro_text),
    );

    $form['question01'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('1. If $20,000 came to me unexpectedly, my first impulse would be to:'),
      '#options' => array(
        'S' => t("Spend it on things I want, including gifts for others."),
        'H' => t("Immediately put it somewhere safe so it won't get frittered away."),
        'V' => t("Put off making any decisions until I felt less overwhelmed."),
        'A' => t("Figure out ways of investing it to get the best possible return."),
        'M' => t("Give most of it away to organizations that can make the world a better place.")
      ),
    );
    $form['question02'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('2. When it comes to dealing with my money:'),
      '#options' => array(
        'M' => t("I make sure it never influences my life choices."),
        'S' => t("I enjoy spending it on gifts and anything else that gives me pleasure."),
        'A' => t("I think about it a lot and strategize how to make more of it."),
        'H' => t("I hold onto it and enjoy thinking about the security it provides."),
        'V' => t("I try not to think about it and hope it will take care of itself.")
      ),
    );
    $form['question03'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('3. My primary financial objective is:'),
      '#options' => array(
        'H' => t("To save enough money now so I never have to worry about my old age."),
        'V' => t("Unclear to me."),
        'S' => t("To have enough of it to ensure that I can buy whatever I want."),
        'M' => t("To have enough to satisfy my basic needs, and then give the rest away."),
        'A' => t("To make as much of it as possible, as quickly as possible.")
      ),
    );
    $form['question04'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('4. When it comes to budgeting my money:'),
      '#options' => array(
        'A' => t("I take a lot of time figuring out how to have more money to spend and save."),
        'H' => t("I take pride in following my budget closely."),
        'M' => t("I take pride in living so simply that I've never needed a budget."),
        'S' => t("Budget? Yuck! Just hearing the word makes me want to rebel."),
        'V' => t("I don't have a budget and wouldn't know how to start making one. I hope my money will take care of itself.")
      ),
    );
    $form['question05'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('5. When it comes to spending:'),
      '#options' => array(
        'V' => t("I hope I have enough money to take care of unexpected expenses."),
        'A' => t("I enjoy spending money, as long as I can keep earning and saving more and my net worth keeps increasing."),
        'H' => t("I'd rather save my money; spending it makes me nervous."),
        'M' => t("I don't care where my money goes; I have more important things to think about."),
        'S' => t("I love spending money, and I tend to spend more than I earn.")
      ),
    );
    $form['question06'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('6. When I think about financial recordkeeping:'),
      '#options' => array(
        'A' => t("I love to look at my old statements to see how much more money I have now."),
        'V' => t("I'm not sure which records I should be keeping."),
        'H' => t("I enjoy keeping careful records."),
        'S' => t("I keep track of things on and off."),
        'M' => t("I don't keep records. There are more important things in life.")
      ),
    );
    $form['question07'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('7. When it comes to saving:'),
      '#options' => array(
        'V' => t("I know I ought to be saving money, but I never seem to get around to it."),
        'A' => t("I really enjoy saving, and often think about how I could save more."),
        'S' => t("I have trouble saving money, which bothers me sometimes."),
        'M' => t("If I had enough money to save, I'd give it away instead."),
        'H' => t("Saving comes naturally to me. I am regular and consistent about it.")
      ),
    );
    $form['question08'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('8. When it comes to borrowing:'),
      '#options' => array(
        'V' => t("I try not to borrow money because it's easy to lose track of paying it back."),
        'H' => t("It's rare for me to borrow money, because I always have enough saved for emergencies."),
        'A' => t("I'm willing to borrow money to make money, but I dislike having lots of debt."),
        'S' => t("I've borrowed money quite often, but I can't say I've always paid it back."),
        'M' => t("I hate debt and would borrow only for absolute necessities.")
      ),
    );
    $form['question09'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('9. When it comes to lending money:'),
      '#options' => array(
        'S' => t("I'm pretty generous and don't worry too much about getting it back."),
        'M' => t("People tend not to ask me for money. They know I probably don't have any extra."),
        'V' => t("I have no idea whether I could afford to lend anyone money."),
        'H' => t("I try never to lend money, but if I do, I feel tense about it until it's repaid."),
        'A' => t("I don't mind lending money at a good interest rate, if I get repaid on time.")
      ),
    );
    $form['question10'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('10. As far as credit cards are concerned:'),
      '#options' => array(
        'M' => t("I don't like to use credit cards, and think that people who do are asking for trouble."),
        'S' => t("I use credit cards a lot and tend to make the minimum payment most of the time."),
        'A' => t("I don't mind running up a large balance, as long as I can pay it off quickly."),
        'V' => t("I'm often surprised by how much I owe, especially when late fees are added in."),
        'H' => t("I've always tended to avoid using credit. I prefer paying by debit card or cash.")
      ),
    );
    $form['question11'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('11. In the event of a financial emergency:'),
      '#options' => array(
        'V' => t("I don't know if I have enough saved, so I just hope for the best."),
        'M' => t("I hope I could rely on friends or bartering services."),
        'S' => t("I never have enough money left over to save for emergencies."),
        'A' => t("I've put aside a sizable amount for emergencies, but I'm not sure it's enough."),
        'H' => t("I've saved enough for almost any emergency, but hope I never have to spend it.")
      ),
    );
    $form['question12'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('12. As far as paying taxes is concerned:'),
      '#options' => array(
        'V' => t("I'm always astonished to find out how much tax I owe."),
        'H' => t("I save regularly for taxes, and usually file my return well before it's due."),
        'M' => t("I hate the whole thing and try to get it done with as little fuss as possible."),
        'S' => t("I always have to scramble to get my return done and find cash to pay my taxes."),
        'A' => t("I take pride in paying less on my increased income, if I can.")
      ),
    );
    $form['question13'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('13. To feel totally satisfied with my annual income, I would need:'),
      '#options' => array(
        'H' => t("My employer to match every dollar I put into my 401(k)"),
        'A' => t("At least twice as much as I'm earning now."),
        'V' => t("I'm sure I could use more money, but I have no idea how much."),
        'M' => t("I'm fine the way I am. More money would make me feel uncomfortable."),
        'S' => t("To have someone else pay my bills, so I can spend the whole paycheck!")
      ),
    );
    $form['question14'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('14. When it comes to investing:'),
      '#options' => array(
        'A' => t("I always let my dividends compound to maximize my return."),
        'V' => t("If I were to invest, I'd want someone else to make all the decisions for me."),
        'H' => t("I only invest in safe, conservative choices like CDs."),
        'S' => t("I've always wanted to try something wild that might end up making me rich."),
        'M' => t("If I were to invest, I would choose only socially responsible companies.")
      ),
    );
    $form['question15'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t("When I really want to buy something that's not in my budget:"),
      '#options' => array(
        'V' => t("What budget? Everything will work out all right."),
        'H' => t("I'd have to think hard before giving myself permission to spend the money."),
        'S' => t("I'll buy it whether or not I can afford it."),
        'M' => t("Most of the things I want are not expensive, so I can afford to buy them (even though later on I'll probably wish I hadn't)"),
        'A' => t("If it's important enough, I'll tweak my portfolio. Otherwise, I'll forget about it.")
      ),
    );
    $form['question16'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('16. When I think about money in general, to me it represents:'),
      '#options' => array(
        'H' => t("Security."),
        'S' => t("Happiness, pleasure, and excitement."),
        'M' => t("A sense of greed and possibly corruption."),
        'V' => t("A source of anxiety and conflict."),
        'A' => t("Power, prestige, and freedom.")
      ),
    );
    $form['question17'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('17. I would apply for a bank loan under these circumstances:'),
      '#options' => array(
        'S' => t("To go on vacation or buy something I really wanted."),
        'M' => t("Only if it were a dire emergency. I hope I'll never have to borrow money."),
        'A' => t("To invest in a business or some other high-yielding opportunity."),
        'H' => t("To make essential repairs, pay off debt, or increase my future security."),
        'V' => t("I don't know.")
      ),
    );
    $form['question18'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('18. I worry about money:'),
      '#options' => array(
        'M' => t("Never. I worry about more important things, like global warming."),
        'A' => t("Somewhat, but I'm doing all I can to make sure I'll have more than enough."),
        'H' => t("Constantly. It's the main thing I worry about."),
        'V' => t("Only when a financial crisis strikes."),
        'S' => t("What, me worry? I just enjoy spending it!")
      ),
    );
    $form['question19'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('19. When I think about providing for my future:'),
      '#options' => array(
        'S' => t("I'm quite concerned, since it's been so hard for me to save."),
        'V' => t("All I can do is hope the future will take care of itself."),
        'A' => t("Since I'm planning to have plenty of money, the future will probably be fine."),
        'H' => t("I feel reasonably confident, since I've been saving systematically for years."),
        'M' => t("I think making a difference with one's life is much more important than money.")
      ),
    );
    $form['question20'] = array(
      '#type' => 'radios',
      //'#required' => TRUE,
      '#title' => t('20. If I won a million dollars in the lottery, my first reaction would be:'),
      '#options' => array(
        'M' => t("To feel guilty, thinking about impoverished people who have nothing."),
        'H' => t("To feel relieved that my future was now secure."),
        'V' => t("To be totally overwhelmed. I would have no idea how to handle it."),
        'A' => t("To start thinking about ways to make it grow and use it for my own enjoyment."),
        'S' => t("To be wildly excited, realizing that from now on I could buy anything I wanted.")
      ),
    );

    $form['results'] = array(
      '#type' => 'hidden',
      '#value' => ''
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'What is my Money type?',
    );
  }

  return $form;
}

// Alt. response page method using redirect and should work with hook_menu - skipping this part
// and putting output directly in hook_form.
/**
 * Implementation of hook_form_alter().
 */
/*
function mhquiz_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "mhquiz_form") {
    $form['#submit'][] = '_mhquiz_redirect_handler';
  }
}
*/

/**
 * Attaches the redirect to the submitted form.
 */
/*
function _mhquiz_redirect_handler(&$form, &$form_state) {
  $form_state['redirect'] = 'moneyharmony-quiz/results';
}
*/

function mhquiz_form_submit($form, &$form_state) {
  //debug_print_backtrace();
  //$e = new Exception;
  //var_dump($e->getTraceAsString());

  /* Five types: */
  $typeA = "Amasser";
  $typeV = "Avoider";
  $typeH = "Hoarder";
  $typeM = "Money Monk";
  $typeS = "Spender";

  // now tabulate the answers
  $cntH = $cntS = $cntV = $cntA = $cntM = 0;

  foreach($form_state['values'] as $key=>$Ans) {
    if (strstr($key, 'question')) {
      if ($Ans == "H") {
        $cntH++;
      }
      elseif ($Ans == "S") {
        $cntS++;
      }
      elseif ($Ans == "M") {
        $cntM++;
      }
      elseif ($Ans == "V") {
        $cntV++;
      }
      elseif ($Ans == "A") {
        $cntA++;
      }
    }
  }

  // now find highest sum - logic goes here
  $a = array("H" => $cntH, "S" => $cntS, "M" => $cntM, "V" => $cntV, "A" => $cntA);
  $cc = array("H" => $cntH, "S" => $cntS, "M" => $cntM, "V" => $cntV, "A" => $cntA);
  sort($a); // reverse sort to put highest count last
  $bb = $a[4];
  $Result = array_search($bb, $cc);

  if ($Result == "S") {
    $Result = $typeS;
  }
  elseif ($Result == "M") {
    $Result = $typeM;
  }
  elseif ($Result == "V") {
    $Result = $typeV;
  }
  elseif ($Result == "A") {
    $Result = $typeA;
  }
  elseif ($Result == "H") {
    $Result = $typeH;
  }

  if ($bb == $a[3]) { // if 2nd to last array element = last element, there's a tie
    $Prefix = "-";
    $Suffix = "-";
    $Result = "Inconclusive";
  }

  // pass in amounts for output
  $form_state['values']['results'] = array(
    'tabulation' => array(
      $typeA => $cntA,
      $typeH => $cntH,
      $typeM => $cntM,
      $typeS => $cntS,
      $typeV => $cntV
    ),
    'tabulation_raw' => $a,
    'winner' => $Result,
    'incomplete_quiz' => '',
    'block_delta' => array(
      "Amasser" => 3,
      "Avoider" => 4,
      "Hoarder" => 5,
      "Money Monk" => 6,
      "Spender" => 7
    ),
  );
  // Rebuild the form
  $form_state['rebuild'] = TRUE;
}

/**
 * Render the results output and return
 */
function _mhquiz_results_output($results) {
  $output = <<<END
<div class='QRMain'>

<h3>Moneyharmony Quiz - RESULTS</h3>

END;

  if ($results['winner'] == "Inconclusive") {
    $output .=  "<h4>Based on your responses, the test is inconclusive because you have a tied high score for more than one category. Compare the scores above to see which money types you match the most, or <a href='/moneyharmony-quiz'>retake the test</a>.</h4>\n\n";
  }

  else {
    $output .= "<h3>Based on your responses, you have the most in common with the following money personality: <span style='color: red;'>" . $results['winner'] . "</span></h3>\n\n";

    $output .= "<p>Here is an excerpt from <a href=\"/books-resources#mhrmc\">Money Harmony: Resolving Money Conflicts In Your Life and Relationships</a> about the <span style='color: red;'>" . $results['winner'] . "</span> money personality type:</em></p>\n\n";

    // output explanation text from blocks
    $block_top_money_type = $results['winner'];
    $block = module_invoke('block', 'block_view', $results['block_delta'][$block_top_money_type]);
    $output .= "<blockquote class='your-money-type'>" . render($block['content']) . "</blockquote>";
  }

  $output .= '  <div class="QRDiv">' . "\n\n";
  $output .= "  <h3>Quiz responses by money personality type:</h3>\n\n";

  $output .= '<ul id="Res">' . "\n";

  arsort($results['tabulation']); // sort, most to least responses
  foreach($results['tabulation'] as $type => $amt) {
    // TODO - theme_results for this list
    $output .= '<li><a href="/moneyharmony-quiz/show-all-types#' . str_replace(' ', '', $type) . '">' . $type . '</a>: <strong>' . $amt . ' response' . ($amt > 1 ? "s" : "") . '</strong></li>' . "\n";
  }
  $output .= "</ul>\n";

  $output .= "  </div>\n";

  $output .= <<<END

  <p>Do you want to see the descriptive results for all five money personality types in this quiz? Go <a href="/moneyharmony-quiz/show-all-types">here</a>.</p>

  <p>There are also <strong>additional</strong> money types that are not included in this quiz. There are Money Worriers, and when it comes to
  couples, Money Mergers and Money Separatists, Planners and Dreamers, Risk Takers and Risk Avoiders. An understanding
  of this quiz's five money types, however, is a great way to start getting to know your own money personality.</p>

  <p>To find out more about all of the money personality types,
  check out Chapter Four of <a href="/books-resources#mhrmc">Money Harmony: A Road Map for Individuals and Couples</a>, by Olivia Mellan
  and Sherry Christie.</p>

</div>

<p>Return to the <a href="/moneyharmony-quiz">Money Personality Quiz</a></p>

END;

  return $output;

}