<?php
// Plugin definition
$plugin = array(
  'title' => t('Money Hewston Flipped (deprecated)'),
  'icon' => 'money-hewston-flipped.png',
  'category' => t('Moneyharmony Custom'),
  'theme' => 'money_hewston_flipped',
  'regions' => array(
    'slider' => t('Slider'),
    'slidergutter' => t('Slider Gutter'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
  ),
);
