<?php

/**
 * Implements hook_views_pre_render().
 */
function mh_extras_views_pre_render(&$view) {
  if ($view->name === "fp_slider") {
    // Update the slide title for ThinkAdvisor articles.
    dpm($view, __FUNCTION__);
    $first_title_set = 0;
    foreach ($view->result as $slide) {
      if (!empty($slide->field_field_published_date)) {
        // Olivia's Latest from ThinkAdvisor
        if ($first_title_set === 0) {
          $slide->node_title = "Olivia's Latest from ThinkAdvisor - " . $slide->node_title;
          $first_title_set++;
        }
        else {
          $title_prefix = "";
          foreach ($slide->field_field_category_slider as $term => $value) {
            // Tagged as Special Article
            if ($value['rendered']['#title'] === 'Special Article') {
              $title_prefix = "ThinkAdvisor.com Special Article - ";
              break;
            }
            if ($value['rendered']['#title'] === 'ThinkAdvisor') {
              // Only tagged as Think Advisor.com
              $title_prefix = "From ThinkAdvisor.com - ";
              continue;
            }
          }
          $slide->node_title = $title_prefix . $slide->node_title;
        }
      }
      else {
        // Do nothing...
      }
    }
  }
}
#Olivia's Latest from ThinkAdvisor — $view->result[4]->field_field_published_date[0]['raw']['value']
# views-view-field--fp-slider--panel-pane--title.tpl.php